package jdolly;

public enum BodyType {
	METHOD_INVOCATION, FIELD_INVOCATION, CONSTRUCTOR_METHOD_INVOCATION, CONSTRUCTOR_FIELD_INVOCATION, CLASS_METHOD_INVOCATION, CLASS_FIELD_INVOCATION, INT_CONSTANT_VALUE
}
